version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: hypernext
  ignore:
  - dependency-name: snyk
    versions:
    - ">= 0"
  - dependency-name: ts-loader
    versions:
    - 8.0.15
    - 8.0.17
    - 8.1.0
    - 9.1.1
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.13.0
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.6
  - dependency-name: jsoneditor
    versions:
    - 9.1.10
    - 9.2.0
    - 9.3.0
    - 9.3.1
    - 9.4.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.13
    - 7.13.15
    - 7.13.16
    - 7.13.8
  - dependency-name: webpack
    versions:
    - 5.21.2
    - 5.25.1
    - 5.27.1
    - 5.30.0
    - 5.31.2
    - 5.35.1
  - dependency-name: mathjax-full
    versions:
    - 3.1.4
  - dependency-name: css-loader
    versions:
    - 5.2.1
    - 5.2.4
  - dependency-name: grunt
    versions:
    - 1.4.0
  - dependency-name: marked
    versions:
    - 2.0.0
    - 2.0.3
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.15
    - 7.13.8
  - dependency-name: "@types/file-saver"
    versions:
    - 2.0.2
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: "@types/luxon"
    versions:
    - 1.26.3
  - dependency-name: dropzone
    versions:
    - 5.7.4
    - 5.8.0
    - 5.9.2
  - dependency-name: i18next
    versions:
    - 19.8.7
    - 20.1.0
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
    - 4.6.0
  - dependency-name: "@types/bootstrap"
    versions:
    - 5.0.12
    - 5.0.8
    - 5.0.9
  - dependency-name: apidoc
    versions:
    - 0.27.1
  - dependency-name: 3dmol
    versions:
    - 1.6.3
  - dependency-name: grunt-contrib-cssmin
    versions:
    - 4.0.0
  - dependency-name: "@types/jqueryui"
    versions:
    - 1.12.15
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: stylelint-config-sass-guidelines
    versions:
    - 8.0.0
  - dependency-name: expose-loader
    versions:
    - 2.0.0
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: hypernext
  ignore:
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.4
    - 2.18.5
    - 2.18.6
  - dependency-name: codeception/module-webdriver
    versions:
    - 1.2.1
  - dependency-name: directorytree/ldaprecord
    versions:
    - 2.1.1
    - 2.1.2
    - 2.1.3
    - 2.2.0
    - 2.3.0
    - 2.4.1
    - 2.4.3
  - dependency-name: codeception/module-rest
    versions:
    - 1.2.8
    - 1.3.0
    - 1.3.1
  - dependency-name: league/csv
    versions:
    - 9.7.0
    - 9.7.1
  - dependency-name: defuse/php-encryption
    versions:
    - 2.3.1
  - dependency-name: codeception/codeception
    versions:
    - 4.1.17
    - 4.1.18
    - 4.1.19
    - 4.1.20
  - dependency-name: league/commonmark
    versions:
    - 1.5.8
  - dependency-name: onelogin/php-saml
    versions:
    - 3.6.0
    - 4.0.0
  - dependency-name: symfony/filesystem
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/http-foundation
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/mime
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: swiftmailer/swiftmailer
    versions:
    - 6.2.6
  - dependency-name: symfony/yaml
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/console
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/process
    versions:
    - 5.2.3
    - 5.2.4
