---
version: "2"
plugins:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  phan:
    enabled: true
    config:
      file_extensions: "php"
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
exclude_patterns:
- web/app/js/chemdoodle
- web/app/js/langs
- web/app/js/mathjax
- web/app/js/plugins
- web/app/js/skins
- web/app/js/src/prism.js
- web/app/js/src/3Dmol-nojquery.js
- web/app/js/themes
- vendor/*
- tests/*
