build:
    environment:
        docker:
            cache:
                images:
                    - 'elabftw/elabimg:hypernext'
                    - 'mysql:8.0'

    nodes:
        tests:
            dependencies:
                override:
                    - cp tests/config-ci.php config.php
                before:
                    - echo do nothing here

    tests:
        override:
            - command: docker version
            - command: tests/run.sh unit
              coverage:
                  file: tests/_output/coverage.xml
                  format: clover

