name: Bug report (sysadmin)
description: Bug report form for issues related to the full software suite, its installation, maintenance, etc... Use this if you are a Sysadmin with shell access.
labels: [bug]
body:
  - type: markdown
    id: welcome
    attributes:
      value: "Hello"
  - type: textarea
    id: description
    attributes:
      label: Detailed description of the problem
      description: |
        In this section, please try to concentrate on observations. Only describe what you observed directly.
      validations:
        required: true
  - type: textarea
    id: possible-cause
    attributes:
      label: Do you have any idea what may have caused this?
      description: |
        Simply leave this empty if you do not.
