name: Feature request
description: I have a suggestion!
labels: ['feature request']
body:
  - type: checkboxes
    id: pro-support
    attributes:
      label: Do you have PRO Support or are using the PRO Hosted version?
      options:
        - label: Yes
        - label: No
        - label: I don't know
